name: whanos
services:
  jenkins:
    build:
      context: jenkins
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
      - ./images:/var/jenkins_home/images
      - ./tests:/var/jenkins_home/tests
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/var/jenkins_home/config.yml
      - USER_CHOCOLATEEN_PASSWORD=1234
      - USER_VAUGIE_G_PASSWORD=1234
      - USER_I_DONT_KNOW_PASSWORD=1234
      - USER_NASSO_PASSWORD=1234
