FROM alpine:latest AS install_interpretor

WORKDIR /build

RUN apk add --no-cache bash

SHELL ["/bin/bash", "-c"]

RUN apk add --no-cache make git gcc musl-dev

RUN git clone https://git.catseye.tc/Befunge-93 .

RUN make bin/bef


FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache bash

SHELL ["/bin/bash", "-c"]

COPY --from=install_interpretor /build/bin/bef .

COPY ./app/main.bf .

CMD ["./bef", "main.bf"]