FROM maven:3.9.9-eclipse-temurin-21-alpine

WORKDIR /app

RUN apk add --no-cache bash

SHELL ["/bin/bash", "-c"]

COPY ./app/pom.xml .

COPY ./app/src ./src

ONBUILD RUN mvn package

ONBUILD RUN cp ./target/app.jar .
