FROM gcc:13.3

SHELL ["/bin/bash", "-c"]

WORKDIR /app

COPY ./Makefile .

COPY ./app ./app

RUN make && make clean

RUN find . -name "*.c" -type f -delete
RUN find . -name "*.h" -type f -delete

CMD ["./compiled-app"]
