security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false

jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."

  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - name: Hugo
          id: chocolateen
          password: ${USER_CHOCOLATEEN_PASSWORD}
        - name: Garance
          id: vaugie_g
          password: ${USER_VAUGIE_G_PASSWORD}
        - name: Jeremy
          id: i_dont_know
          password: ${USER_I_DONT_KNOW_PASSWORD}
        - name: Nassim
          id: nasso
          password: ${USER_NASSO_PASSWORD}

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: admin
            description: ""
            permissions:
              - Overall/Administer
            entries:
              - user: chocolateen
          - name: ape
            description: ""
            permissions:
              - Overall/Read
              - Job/Read
              - Job/Build
              - Job/Workspace
            entries:
              - user: i_dont_know
          - name: gorilla
            description: ""
            permissions:
              - Overall/Read
              - Job/Build
              - Job/Read
              - Job/Workspace
              - Job/Delete
              - Job/Create
              - Job/Configure
              - Job/Move
              - Job/Cancel
            entries:
              - user: vaugie_g
          - name: assist
            description: ""
            permissions:
              - Overall/Read
              - Job/Read
              - Job/Workspace
            entries:
              - user: nasso
jobs:
  - file: /var/jenkins_home/job_dsl.groovy