FROM python:3.12-alpine

WORKDIR /app

RUN apk add --no-cache bash

SHELL ["/bin/bash", "-c"]

COPY ./requirements.txt .

COPY ./app ./app

RUN pip install -r requirements.txt

CMD ["python", "-m", "app"]