FROM node:20.9-alpine

RUN apk add --no-cache bash

SHELL ["/bin/bash", "-c"]

ONBUILD WORKDIR /app

ONBUILD COPY ./package.json .

ONBUILD COPY ./package-lock.json .

ONBUILD COPY ./app ./app

ONBUILD RUN ["npm", "i"]
